# Data parameters
# "HR-mix1", "HR-single", "LR-mix2", "LR-single", "HR-all", "LR-all", "test"
data:
  data_type: "HR-mix1"
  data_path: "/home/xiaoman/Projects/Datasets/"

# Model parameters
model:
  model: "MobileNetV2"
  window_size: null

# MobileNetV2 parameters
mobilenetv2:
  width_mult: 1.0
  num_classes: 2

# Training parameters
training:
  epochs: 300
  batch_size: 1024
  lr: 1.0e-3
  optimizer: "Adam"
  momentum: 0.9

# Test parameters
test:
  n_runs: 20
  checkpoint_mode: "both"         # ADINet 常用同时测试 best/last
  checkpoint_path: null
  model_save_format: "state_dict" # ADINet 分支保存为 state_dict

# System parameters
system:
  device: "cuda"
  log_interval: 1
  save_interval: 20
  # windows: "E:/AFCI/checkpoints"
  # linux: "/home/xiaoman/Projects/AFCI/checkpoints"
  save_path: "/root/Projects/AFCI/checkpoints"