# Data parameters
# "HR-mix1", "HR-single", "LR-mix2", "LR-single", "HR-all", "LR-all", "test"
data:
  data_type: "HR-all"
  data_path: "/home/xiaoman/Projects/Datasets/"

# Model parameters
model:
  model: "MobileNetV2"
  window_size: null

# MobileNetV2 parameters
mobilenetv2:
  width_mult: 1.0
  num_classes: 2

# Training parameters
training:
  epochs: 100
  batch_size: 512
  lr: 1.0e-3
  optimizer: "Adam"
  momentum: 0.9

# Test parameters
test:
  n_runs: 5
  checkpoint_mode: "both"
  checkpoint_path: null
  model_save_format: "full_model"

# System parameters
system:
  device: "cuda"
  log_interval: 1
  save_interval: 10
  save_path: "/home/xiaoman/Projects/AFCI/checkpoints/master/MobileNetV2/HR-all"
